import { useEffect, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { Heading } from "../components/ui";
import { useNative } from "../services/native";

interface SavedServer { id:string; name:string; address:string; favorite:boolean; telemetryToken?:string; telemetryConnected?:boolean; telemetryPort?:number }
interface ServerStatus { address:string; latencyMs:number; version:string; protocol:number; motd:string; playersOnline:number; playersMax:number; players:{name:string;id:string}[] }
interface TelemetryPlayer { id:string; name:string; kills:number; mobKills:number; deaths:number; playTimeSeconds:number; distanceCm:number; blocksPlaced:number }
interface Telemetry { schema:number; generatedAt:string; online:number; max:number; players:TelemetryPlayer[] }
const storageKey="gaminghub.minecraftServers.v1";
const playTime=(seconds:number)=>`${Math.floor(seconds/3600)} Std. ${Math.floor(seconds%3600/60)} Min.`;
const distance=(cm:number)=>cm>=100000?`${(cm/100000).toLocaleString("de-DE",{maximumFractionDigits:1})} km`:`${Math.round(cm/100)} m`;

export default function Modrinth(){
  const {native}=useNative(); const [tab,setTab]=useState<"server"|"launcher">("server"); const [adding,setAdding]=useState(false); const [busy,setBusy]=useState(false);
  const [error,setError]=useState(""); const [telemetryError,setTelemetryError]=useState(""); const [message,setMessage]=useState("");
  const [name,setName]=useState(""); const [address,setAddress]=useState(""); const [token,setToken]=useState(""); const [port,setPort]=useState(8765);
  const [servers,setServers]=useState<SavedServer[]>(()=>{try{const value=JSON.parse(localStorage.getItem(storageKey)||"[]");return Array.isArray(value)?value.filter(item=>item&&typeof item.id==="string"&&typeof item.name==="string"&&typeof item.address==="string"):[]}catch{return[]}}); const [selected,setSelected]=useState(()=>servers[0]?.id||"");
  const [statuses,setStatuses]=useState<Record<string,ServerStatus>>({}); const [telemetries,setTelemetries]=useState<Record<string,Telemetry>>({});
  const server=servers.find(item=>item.id===selected); const status=selected?statuses[selected]:undefined; const telemetry=selected?telemetries[selected]:undefined;
  const save=(next:SavedServer[])=>{setServers(next);localStorage.setItem(storageKey,JSON.stringify(next))};
  async function loadTelemetry(target:SavedServer){if(!target.telemetryConnected&&!target.telemetryToken)return;try{const data=await invoke<Telemetry>("minecraft_telemetry",{address:target.address,port:target.telemetryPort||8765,serverId:target.id});setTelemetries(old=>({...old,[target.id]:data}));setTelemetryError("")}catch(reason){setTelemetryError(String(reason))}}
  async function refresh(target=server){if(!target||!native)return;setBusy(true);setError("");try{const data=await invoke<ServerStatus>("minecraft_server_status",{address:target.address});setStatuses(old=>({...old,[target.id]:data}));await loadTelemetry(target)}catch(reason){setError(String(reason))}finally{setBusy(false)}}
  useEffect(()=>{if(tab==="server"&&server)void refresh(server);const timer=window.setInterval(()=>{if(tab==="server"&&server)void refresh(server)},30000);return()=>clearInterval(timer)},[selected,tab,native]);
  useEffect(()=>{const legacy=servers.filter(item=>item.telemetryToken);if(!native||!legacy.length)return;void (async()=>{const migrated=await Promise.all(servers.map(async item=>{if(!item.telemetryToken)return item;try{await invoke("minecraft_save_telemetry_token",{serverId:item.id,token:item.telemetryToken});const {telemetryToken:_,...safe}=item;return {...safe,telemetryConnected:true}}catch{return item}}));save(migrated)})()},[native]);
  function add(){if(!address.trim()){setError("Bitte eine Server-IP oder Domain eingeben.");return}const item:SavedServer={id:crypto.randomUUID(),name:name.trim()||address.trim(),address:address.trim(),favorite:false,telemetryPort:port};save([...servers,item]);setSelected(item.id);setName("");setAddress("");setToken("");setAdding(false);setError("")}
  async function connectTelemetry(){if(!server||!/^[a-f0-9]{48}$/i.test(token.trim())){setTelemetryError("Bitte den 48-stelligen Token aus config/gaminghub-telemetry.json eingeben.");return}try{await invoke("minecraft_save_telemetry_token",{serverId:server.id,token:token.trim()});const updated={...server,telemetryConnected:true,telemetryPort:port};save(servers.map(item=>item.id===server.id?updated:item));setToken("");await loadTelemetry(updated)}catch(reason){setTelemetryError(String(reason))}}
  async function start(command:string,label:string){try{await invoke(command);setMessage(`${label} wurde gestartet.`);setError("")}catch(reason){setError(String(reason))}}
  return <>
    <Heading eyebrow="MINECRAFT-MODUL" title="Minecraft">Launcher, Fabric-Server und deine Community an einem Ort.</Heading>
    <div className="minecraft-tabs"><button className={tab==="server"?"active":""} onClick={()=>setTab("server")}>◉ Server</button><button className={tab==="launcher"?"active":""} onClick={()=>setTab("launcher")}>◇ Launcher</button></div>
    {tab==="launcher"&&<section className="panel form-panel modrinth-launch-panel"><div className="modrinth-mark">◇</div><h2>Launcher auswählen</h2><p>Öffne deinen bevorzugten Minecraft-Launcher direkt aus GamingHub.</p><div className="toolbar"><button className="primary" onClick={()=>void start("open_modrinth","Modrinth")}>▶ Modrinth starten</button><button className="secondary" onClick={()=>void start("open_labymod","LabyMod Launcher")}>▶ LabyMod starten</button></div>{message&&<p className="feedback">{message}</p>}{error&&<p className="notice">{error}</p>}</section>}
    {tab==="server"&&<div className="minecraft-server-layout">
      <aside className="panel minecraft-server-list"><div className="section-title"><div><span className="eyebrow">DEINE WELTEN</span><h2>Server</h2></div><button className="minecraft-add" onClick={()=>setAdding(true)}>＋</button></div>{servers.length?servers.map(item=><button className={selected===item.id?"active":""} key={item.id} onClick={()=>setSelected(item.id)}><span className={statuses[item.id]?"server-dot online":"server-dot"}/><div><strong>{item.name}</strong><small>{item.address}</small></div><i>{item.favorite?"★":"›"}</i></button>):<div className="minecraft-empty"><span>◈</span><strong>Noch kein Server</strong><p>Füge deinen Fabric-Server über seine Adresse hinzu.</p><button className="primary" onClick={()=>setAdding(true)}>Server hinzufügen</button></div>}</aside>
      <div className="minecraft-dashboard">{!server?<section className="panel minecraft-welcome"><span>◈</span><h2>Dein Server-Dashboard</h2><p>Speichere einen Minecraft-Java-Server, um Status und Spieler zu sehen.</p></section>:<>
        <section className="panel minecraft-server-hero"><div><span className="eyebrow">{status?"● SERVER ONLINE":"○ STATUS UNBEKANNT"}</span><h2>{server.name}</h2><p>{status?.motd||server.address}</p></div><div className="server-hero-actions"><button className={server.favorite?"favorite":""} onClick={()=>save(servers.map(item=>item.id===server.id?{...item,favorite:!item.favorite}:item))}>★</button><button className="secondary" disabled={busy} onClick={()=>void refresh()}>{busy?"Prüft …":"↻ Aktualisieren"}</button><button className="text-button danger-text" onClick={()=>{void invoke("minecraft_forget_telemetry_token",{serverId:server.id});const next=servers.filter(item=>item.id!==server.id);save(next);setSelected(next[0]?.id||"")}}>Entfernen</button></div></section>
        {error&&<p className="notice">{error}</p>}
        <div className="minecraft-metrics"><section className="panel"><span>SPIELER</span><strong>{status?`${status.playersOnline} / ${status.playersMax}`:"–"}</strong><small>Aktuelle Auslastung</small></section><section className="panel"><span>PING</span><strong>{status?`${status.latencyMs} ms`:"–"}</strong><small>Server-Latenz</small></section><section className="panel"><span>VERSION</span><strong>{status?.version||"–"}</strong><small>Protokoll {status?.protocol||"–"}</small></section><section className="panel"><span>TELEMETRIE</span><strong>{telemetry?"Verbunden":"Basis"}</strong><small>{telemetry?"Fabric-Mod aktiv":"Token einrichten"}</small></section></div>
        {!telemetry&&<section className="panel telemetry-connect"><div><span className="eyebrow">FABRIC-ERWEITERUNG</span><h2>Spielerstatistiken verbinden</h2><p>Trage den Token aus <code>config/gaminghub-telemetry.json</code> ein. GamingHub schützt ihn anschließend im Windows-Anmeldespeicher.</p></div><div className="telemetry-fields"><input type="password" placeholder="48-stelliger Telemetrie-Token" value={token} onChange={event=>setToken(event.target.value)}/><div className="timer-adjust"><button onClick={()=>setPort(value=>Math.max(1,value-1))}>−</button><strong>Port {port}</strong><button onClick={()=>setPort(value=>Math.min(65535,value+1))}>＋</button></div><button className="primary" onClick={()=>void connectTelemetry()}>Telemetrie verbinden</button></div>{telemetryError&&<p className="notice">{telemetryError}</p>}</section>}
        <section className="panel minecraft-players"><div className="section-title"><div><h2>Spieler-Dashboard</h2><p className="muted">Kills, Spielzeit, Strecke und platzierte Blöcke</p></div><span className="pill neutral">{telemetry?.online??status?.playersOnline??0} ONLINE</span></div>{telemetry?.players.length?<div className="minecraft-player-table"><div className="player-table-head"><span>Spieler</span><span>Kills / Tode</span><span>Spielzeit</span><span>Strecke / Blöcke</span></div>{telemetry.players.map(player=><div className="player-table-row" key={player.id}><span><i>{player.name[0]?.toUpperCase()}</i><strong>{player.name}</strong></span><span>{player.kills} / {player.deaths}<small>{player.mobKills} Mob-Kills</small></span><span>{playTime(player.playTimeSeconds)}</span><span>{distance(player.distanceCm)}<small>{player.blocksPlaced.toLocaleString("de-DE")} Blöcke platziert</small></span></div>)}</div>:<div className="minecraft-no-players"><span>♙</span><strong>{telemetry?"Gerade niemand online":"Fabric-Telemetrie noch nicht verbunden"}</strong><p>{telemetry?"Die Tabelle füllt sich automatisch, sobald jemand den Server betritt.":"Die Basisabfrage zeigt Status und Spielerzahl. Für Statistiken installiere die GamingHub-Mod und verbinde ihren Token."}</p></div>}</section>
        <section className="panel minecraft-details"><h2>Serverdetails</h2><div className="detail-row"><span>Adresse</span><span>{status?.address||server.address} <button className="copy-mini" onClick={()=>void navigator.clipboard.writeText(server.address)}>Kopieren</button></span></div><div className="detail-row"><span>Aktualisierung</span><span>Alle 30 Sekunden</span></div><div className="detail-row"><span>Telemetrie</span><span>{server.telemetryConnected?`Sicher verbunden · Port ${server.telemetryPort||8765}`:"Nicht eingerichtet"}</span></div></section>
      </>}</div>
    </div>}
    {adding&&<div className="utility-modal-backdrop" onMouseDown={()=>setAdding(false)}><section className="utility-modal minecraft-add-modal" onMouseDown={event=>event.stopPropagation()}><header><span>◈</span><div><small>MINECRAFT JAVA</small><h2>Server hinzufügen</h2></div><button className="utility-close" onClick={()=>setAdding(false)}>×</button></header><label className="field-label">Anzeigename<input autoFocus value={name} placeholder="Mein Fabric Server" onChange={event=>setName(event.target.value)}/></label><label className="field-label">Server-IP oder Domain<input value={address} placeholder="play.example.net:25565" onChange={event=>setAddress(event.target.value)} onKeyDown={event=>{if(event.key==="Enter")add()}}/></label><p className="field-help">Die Fabric-Telemetrie kannst du nach dem ersten Serverstart verbinden.</p>{error&&<p className="notice">{error}</p>}<button className="primary modal-main" onClick={add}>Server speichern</button></section></div>}
  </>;
}
