import { useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { Heading } from "../components/ui";
import { useNative } from "../services/native";
import GameImagePicker from "../components/GameImagePicker";
type StoreApp = { name: string; aumid: string; cover?: string };
export default function Store() {
  const { native } = useNative();
  const [saved, setSaved] = useState<StoreApp[]>(() => { try { const v=JSON.parse(localStorage.getItem("gaminghub.storeApps.v1")||"[]"); return Array.isArray(v)&&v.every(x=>x&&typeof x.name==="string"&&typeof x.aumid==="string")?v:[]; } catch { return []; } });
  const [name,setName]=useState(""); const [id,setId]=useState(""); const [cover,setCover]=useState<string|undefined>(); const [adding,setAdding]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  async function launch(aumid:string){setError("");try{await invoke("launch_store_app",{aumid});setMessage("Windows-App wurde gestartet.")}catch(e){setError(String(e))}}
  function save(){const app={name:name.trim()||id.trim(),aumid:id.trim(),cover};const next=[...saved.filter(x=>x.aumid!==app.aumid),app];setSaved(next);localStorage.setItem("gaminghub.storeApps.v1",JSON.stringify(next));setMessage(`${app.name} gespeichert.`);setAdding(false);setName("");setId("");setCover(undefined)}
  function updateCover(aumid:string,value?:string){const next=saved.map(x=>x.aumid===aumid?{...x,cover:value}:x);setSaved(next);localStorage.setItem("gaminghub.storeApps.v1",JSON.stringify(next))}
  return <><Heading eyebrow="WINDOWS-APPS" title="Microsoft Store">Starte installierte Store-Programme aus GamingHub.</Heading><button className="secondary store-add-toggle" onClick={()=>setAdding(!adding)}>{adding?"Schließen":"＋ Store-App hinzufügen"}</button>{adding&&<section className="panel form-panel store-panel"><h2>Store-App hinzufügen</h2><p>Die AUMID findest du mit <code>Get-StartApps</code> in PowerShell. Name und ID werden lokal gespeichert.</p><label>Name<input value={name} maxLength={100} placeholder="Taschenrechner" onChange={e=>setName(e.target.value)}/></label><label>Windows-App-ID (AUMID)<input value={id} maxLength={240} placeholder="Microsoft.WindowsCalculator_…!App" onChange={e=>setId(e.target.value)}/></label><GameImagePicker value={cover} onChange={setCover}/><div className="toolbar"><button className="primary" disabled={!native||!id.trim()} onClick={()=>launch(id.trim())}>▶ App starten</button><button className="secondary" disabled={!native||!id.trim()} onClick={save}>App speichern</button></div>{error&&<p className="notice" role="alert">{error}</p>}</section>}{saved.length>0&&<section className="game-grid store-grid">{saved.map(app=><article className="panel game-card" key={app.aumid}><div className={`game-cover cover-${app.name.length%3}`}>{app.cover?<img className="custom-game-cover" src={app.cover} alt={app.name}/>:<span>{app.name.slice(0,2).toUpperCase()}</span>}<small>STORE-APP</small></div><div className="game-info"><h2>{app.name}</h2><p className="path" title={app.aumid}>{app.aumid}</p><details><summary>Bild ändern</summary><GameImagePicker value={app.cover} onChange={v=>updateCover(app.aumid,v)}/></details><button className="primary launch" disabled={!native} onClick={()=>launch(app.aumid)}>▶ Starten</button><button className="text-button remove" onClick={()=>{const next=saved.filter(x=>x.aumid!==app.aumid);setSaved(next);localStorage.setItem("gaminghub.storeApps.v1",JSON.stringify(next));}}>Entfernen</button></div></article>)}</section>}{message&&<p className="feedback" role="status">{message}</p>}{error&&!adding&&<p className="notice" role="alert">{error}</p>}</>;
}
